services:

  ldap:
    image: bitnami/openldap:${LDAP_IMAGE_TAG}
    env_file:
      - .envs/ldap.env
    networks:
      common-net:
        aliases:
          - common-ldap

  ldapadmin:
    image: osixia/phpldapadmin:latest
    networks:
      - common-net
    volumes:
      - ./ldap/admin/env.yaml:/container/environment/01-custom/env.yaml
