networks:
  common-traefik-net:
    external: true

services:

  traefik:
    image: traefik:${TRAEFIK_IMAGE_TAG}
    labels:
      - "traefik.enable=true"
    networks:
      - common-traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
