version: '3.8'

networks:
  common-net:
    external: true

volumes:
  common-minio-data:
    name: 'common-minio-data'
  common-minio-config:
    name: 'common-minio-config'
  common-mysql-db:
    name: 'common-mysql-db'
  common-rabbitmq:
    name: 'common-rabbitmq'
  common-redis:
    name: 'common-redis'

services:
  mysql:
    image: 'mysql:${MYSQL_IMAGE_TAG}'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
    env_file:
      - .envs/mysql.env
    volumes:
      - common-mysql-db:/var/lib/mysql
      - ./sqls:/sqls
    networks:
      common-net:
        aliases:
          - common-mysql

  adminer:
    image: 'adminer:${ADMINER_IMAGE_TAG}'
    env_file:
      - .envs/adminer.env
    depends_on:
      - mysql
    networks:
      - common-net

  redis:
    image: bitnami/redis:${REDIS_IMAGE_TAG}
    env_file:
      - .envs/redis.env
    networks:
      common-net:
        aliases:
          - common-redis
    volumes:
      - common-redis:/bitnami/redis/data

  minio:
    image: minio/minio:${MINIO_IMAGE_TAG}
    command: ["minio", "server", "/data"]
    restart: "no"
    env_file:
      - .envs/minio.env
    networks:
      common-net:
        aliases:
          - common-minio
    volumes:
      - common-minio-data:/data
      - common-minio-config:/root/.minio

  rabbitmq:
    image: rabbitmq:${RABBITMQ_IMAGE_TAG}
    env_file:
      - .envs/rabbitmq.env
    networks:
      common-net:
        aliases:
          - common-rabbitmq
    volumes:
      - common-rabbitmq:/var/lib/rabbitmq
