volumes:
  common-oracle-db:
    name: 'common-oracle-db'

services:

  oracle:
    image: gvenzl/oracle-xe:${ORACLE_IMAGE_TAG:-11.2.0.2-slim}
    tty: true
    env_file:
      - .envs/oracle.env
    volumes:
      - common-oracle-db:${ORACLE_VOLUME_CONTAINER_DIR:-/u01/app/oracle/oradata}
    networks:
      common-net:
        aliases:
          - common-oracle
