services:

  adminer:
    env_file:
      - .envs/http-proxy.env
    ports:
      - ${ADMINER_PUBLISH_PORT}:8080

  cassandra:
    ports:
      - ${CASSANDRA_PUBLISH_PORT}:9042

  elasticsearch:
    env_file:
      - .envs/http-proxy.env
    ports:
      - "${ELASTICSEARCH_PUBLISH_PORT}:9200"

  kibana:
    env_file:
      - .envs/http-proxy.env
    ports:
      - "${KIBANA_PUBLISH_PORT}:5601"

  mailhog:
    ports:
      - "${MAILHOG_PUBLISH_PORT}:8025"

  minio:
    env_file:
      - .envs/http-proxy.env
    ports:
     - ${MINIO_PUBLISH_PORT}:9000

  minio-client:
    volumes:
      - ./minio/policies:/minio-policies

  mysql:
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
      - --local-infile=1
    env_file:
      - .envs/http-proxy.env
    ports:
      - ${MYSQL_PUBLISH_PORT}:3306

  oracle:
    shm_size: 1g
    ports:
      - "${ORACLE_PUBLISH_PORT}:1521"

  redis:
    env_file:
      - .envs/http-proxy.env
    ports:
      - ${REDIS_PUBLISH_PORT}:6379

  redis-slave:
    env_file:
      - .envs/http-proxy.env
    ports:
      - ${REDIS_SLAVE_PUBLISH_PORT}:6379

  redis-sentinel:
    env_file:
      - .envs/http-proxy.env
    ports:
      - ${REDIS_SENTINEL_PUBLISH_PORT}:26379

  redisearch:
    # image: docker.io/your-id/redisearch:${REDISEARCH_IMAGE_TAG}-0
    env_file:
      - .envs/redisearch.env # you can also use the 'redis.env' here
    ports:
      - ${REDISEARCH_PUBLISH_PORT}:6379

  rabbitmq:
    env_file:
      - .envs/http-proxy.env
    ports:
      - ${RABBITMQ_PUBLISH_PORT}:15672

  traefik:
    env_file:
      - .envs/traefik.env
    ports:
      - "80:80"
      - "8080:8080"
