version: '3.8'

services:

  mysql:
    env_file:
      - .envs/http-proxy.env
    ports:
      - 3306:3306

  adminer:
    env_file:
      - .envs/http-proxy.env
    ports:
      - 8080:8080

  redis:
    env_file:
      - .envs/http-proxy.env
    ports:
      - 6379:6379

  redis-slave:
    env_file:
      - .envs/http-proxy.env
    ports:
      - 6380:6379

  redis-sentinel:
    env_file:
      - .envs/http-proxy.env
    ports:
      - 26379:26379

  minio:
    env_file:
      - .envs/http-proxy.env
    ports:
     - 9000:9000

  rabbitmq:
    env_file:
      - .envs/http-proxy.env
    ports:
      - 15672:15672
