version: '3.8'

services:

  mysql:
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
      - --local-infile=1
    env_file:
      - .envs/http-proxy.env
    ports:
      - ${MYSQL_PUBLISH_PORT}:3306

  adminer:
    env_file:
      - .envs/http-proxy.env
    ports:
      - ${ADMINER_PUBLISH_PORT}:8080

  redis:
    env_file:
      - .envs/http-proxy.env
    ports:
      - ${REDIS_PUBLISH_PORT}:6379

  redis-slave:
    env_file:
      - .envs/http-proxy.env
    ports:
      - ${REDIS_SLAVE_PUBLISH_PORT}:6379

  redis-sentinel:
    env_file:
      - .envs/http-proxy.env
    ports:
      - ${REDIS_SENTINEL_PUBLISH_PORT}:26379

  minio:
    env_file:
      - .envs/http-proxy.env
    ports:
     - ${MINIO_PUBLISH_PORT}:9000

  minio-client:
    volumes:
      - ./minio/policies:/minio-policies

  rabbitmq:
    env_file:
      - .envs/http-proxy.env
    ports:
      - ${RABBITMQ_PUBLISH_PORT}:15672

  elasticsearch:
    env_file:
      - .envs/http-proxy.env
    ports:
      - "${ELASTICSEARCH_PUBLISH_PORT}:9200"

  kibana:
    env_file:
      - .envs/http-proxy.env
    ports:
      - "${KIBANA_PUBLISH_PORT}:5601"

  mailhog:
    ports:
      - "${MAILHOG_PUBLISH_PORT}:8025"
