volumes:
  common-mysql-db:
    name: 'common-mysql-db'

services:

  mysql:
    image: 'mysql:${MYSQL_IMAGE_TAG}'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
      - --local-infile=1
    env_file:
      - .envs/mysql.env
    volumes:
      - common-mysql-db:/var/lib/mysql
      - ./mysql/sqls:/sqls
    networks:
      common-net:
        aliases:
          - common-mysql
