version: '3.8'

volumes:
  common-minio-data:
    name: 'common-minio-data'
  common-minio-client-config:
    name: 'common-minio-client-config'

services:

  minio:
    image: minio/minio:${MINIO_IMAGE_TAG}
    command: ["minio", "server", "/data"]
    restart: "no"
    env_file:
      - .envs/minio.env
    networks:
      common-net:
        aliases:
          - common-minio
    volumes:
      - common-minio-data:/data

  minio-client:
    image: minio/mc:${MINIO_CLIENT_IMAGE_TAG}
    command: ["--version"]
    restart: "no"
    depends_on:
      - minio
    networks:
      - common-net
    volumes:
      - common-minio-client-config:/root/.mc
